-- MySQL Script generated by MySQL Workbench
-- Tue Sep 15 22:27:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `itemNo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(30) NOT NULL,
  `qty` INT ZEROFILL NOT NULL DEFAULT 0,
  `costPrice` INT ZEROFILL NOT NULL,
  `selPrice` INT ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`itemNo`),
  UNIQUE INDEX `itemNo_UNIQUE` (`itemNo` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
